title: Aderonke Omotola
logo: Passport.jpg
description: Data Analyst with 5+ years of experience transforming raw data into business solutions. Proficient in SQL for querying and data manipulation, Excel for deep analysis, and Power BI for visual reporting.
#show_downloads: true
#google_analytics:
#theme: jekyll-theme-minimal
